# Generated by Django 4.0.2 on 2022-08-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='deposit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
