# Generated by Django 4.0.2 on 2022-08-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_transactions_remove_accounts_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.accounts'),
        ),
    ]
