# Generated by Django 4.0.2 on 2022-08-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_transactions_id_alter_transactions_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='acc_type',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='overdraft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='trans_limit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=250)),
                ('principle', models.FloatField()),
                ('time_mnths', models.IntegerField()),
                ('rate', models.FloatField()),
                ('acc', models.ManyToManyField(to='staff.Accounts')),
            ],
        ),
    ]
