# Generated by Django 4.0.2 on 2022-08-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_accounts_acc_type_accounts_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='acc',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='acc',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='acc',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Loans',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
