# Generated by Django 4.0.2 on 2022-08-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0007_remove_customers_acc_remove_loans_acc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('acc_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('overdraft', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField()),
                ('trans_limit', models.FloatField()),
                ('acc_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.FloatField(blank=True, null=True)),
                ('withdrawal_amount', models.FloatField(blank=True, null=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=250)),
                ('principle', models.FloatField()),
                ('rate', models.FloatField()),
                ('time_mnths', models.IntegerField()),
                ('acc', models.ManyToManyField(to='staff.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cust_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('pan', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
                ('cust_name', models.CharField(max_length=250)),
                ('acc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.accounts')),
            ],
        ),
    ]
