# Generated by Django 4.0.2 on 2022-08-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.accounts'),
        ),
    ]
